"""empty message

Revision ID: 060d74fd1ce0
Revises: e00f2ee1aefb
Create Date: 2021-03-26 18:11:49.371772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060d74fd1ce0'
down_revision = 'e00f2ee1aefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'facilities', ['facilitycode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facilities', type_='unique')
    # ### end Alembic commands ###
