"""empty message

Revision ID: 59f298387b6a
Revises: 5e3c807fb27d
Create Date: 2021-03-05 20:57:36.176723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f298387b6a'
down_revision = '5e3c807fb27d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('separators_outputs_vessel_gas_capacity_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separator_tag', sa.String(), nullable=False),
    sa.Column('gasloadfactor', sa.String(length=80), nullable=False),
    sa.Column('maximumgasflowathhlevel', sa.String(length=80), nullable=False),
    sa.Column('maximumgasflowatnormallevel', sa.String(length=80), nullable=False),
    sa.Column('statusgascapacityathighlevel', sa.String(length=80), nullable=False),
    sa.Column('statusgascapacityatnormallevel', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['separator_tag'], ['separators.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('separators_outputs_vessel_gas_capacity_parameters')
    # ### end Alembic commands ###
