"""empty message

Revision ID: 5b49ec36ad5e
Revises: 6ed6deccde9d
Create Date: 2021-02-26 19:40:56.818223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b49ec36ad5e'
down_revision = '6ed6deccde9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('separators_inputs_data_fluids_separator_id_key', 'separators_inputs_data_fluids', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('separators_inputs_data_fluids_separator_id_key', 'separators_inputs_data_fluids', ['separator_id'])
    # ### end Alembic commands ###
