"""empty message

Revision ID: 5e3c807fb27d
Revises: 9b3ca0d4f412
Create Date: 2021-03-05 19:24:23.074974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3c807fb27d'
down_revision = '9b3ca0d4f412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('separators_outputs_liquid_nozzle_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separator_tag', sa.String(), nullable=False),
    sa.Column('liquidnozzlevelocity', sa.String(length=80), nullable=False),
    sa.Column('maximumliquidnozzlevelocity', sa.String(length=80), nullable=False),
    sa.Column('maximumliquidnozzleflow', sa.String(length=80), nullable=False),
    sa.Column('statusliquidnozzle', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['separator_tag'], ['separators.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('separators_outputs_liquid_nozzle_parameters')
    # ### end Alembic commands ###
