"""empty message

Revision ID: ad773f2c3ab6
Revises: 
Create Date: 2021-02-21 19:04:56.425832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad773f2c3ab6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('dateofstablish', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=False),
    sa.Column('lastname', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('separators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('user_facilities',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('separators_inputs_data_fluids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separator_id', sa.Integer(), nullable=False),
    sa.Column('operatingpressure', sa.String(length=80), nullable=False),
    sa.Column('operatingtemperature', sa.String(length=80), nullable=False),
    sa.Column('oildensity', sa.String(length=80), nullable=False),
    sa.Column('gasdensity', sa.String(length=80), nullable=False),
    sa.Column('mixturedensity', sa.String(length=80), nullable=False),
    sa.Column('waterdensity', sa.String(length=80), nullable=False),
    sa.Column('feedbsw', sa.String(length=80), nullable=False),
    sa.Column('liquidviscosity', sa.String(length=80), nullable=False),
    sa.Column('gasviscosity', sa.String(length=80), nullable=False),
    sa.Column('gasmw', sa.String(length=80), nullable=False),
    sa.Column('liqmw', sa.String(length=80), nullable=False),
    sa.Column('gascomprz', sa.String(length=80), nullable=False),
    sa.Column('especificheatratio', sa.String(length=80), nullable=False),
    sa.Column('liquidsurfacetension', sa.String(length=80), nullable=False),
    sa.Column('liquidvaporpressure', sa.String(length=80), nullable=False),
    sa.Column('liquidcriticalpressure', sa.String(length=80), nullable=False),
    sa.Column('standardgasflow', sa.String(length=80), nullable=False),
    sa.Column('standardliquidflow', sa.String(length=80), nullable=False),
    sa.Column('actualgasflow', sa.String(length=80), nullable=False),
    sa.Column('actualliquidflow', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['separator_id'], ['separators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('separator_id')
    )
    op.create_table('separators_inputs_data_separators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separator_id', sa.Integer(), nullable=False),
    sa.Column('internaldiameter', sa.String(length=80), nullable=False),
    sa.Column('ttlength', sa.String(length=80), nullable=False),
    sa.Column('highleveltrip', sa.String(length=80), nullable=False),
    sa.Column('highlevelalarm', sa.String(length=80), nullable=False),
    sa.Column('normalliquidlevel', sa.String(length=80), nullable=False),
    sa.Column('lowlevelalarm', sa.String(length=80), nullable=False),
    sa.Column('inletnozzle', sa.String(length=80), nullable=False),
    sa.Column('gasoutletnozzle', sa.String(length=80), nullable=False),
    sa.Column('liquidoutletnozzle', sa.String(length=80), nullable=False),
    sa.Column('inletdevicetype', sa.String(length=80), nullable=False),
    sa.Column('demistertype', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['separator_id'], ['separators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('separator_id')
    )
    op.create_table('separators_outputs_gas_and_liquid_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('separator_id', sa.Integer(), nullable=False),
    sa.Column('separatorcrosssectionalarearatio', sa.String(length=80), nullable=False),
    sa.Column('separatorcrosssectionalarea', sa.String(length=80), nullable=False),
    sa.Column('inletnozzlearea', sa.String(length=80), nullable=False),
    sa.Column('gasnozzlearea', sa.String(length=80), nullable=False),
    sa.Column('liquidnozzlearea', sa.String(length=80), nullable=False),
    sa.Column('highleveltripgasarea', sa.String(length=80), nullable=False),
    sa.Column('normallevelgasarea', sa.String(length=80), nullable=False),
    sa.Column('lowlevelgasarea', sa.String(length=80), nullable=False),
    sa.Column('highleveltripliquidarea', sa.String(length=80), nullable=False),
    sa.Column('normalleveltriparea', sa.String(length=80), nullable=False),
    sa.Column('lowleveltripliquidarea', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['separator_id'], ['separators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('separator_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('separators_outputs_gas_and_liquid_areas')
    op.drop_table('separators_inputs_data_separators')
    op.drop_table('separators_inputs_data_fluids')
    op.drop_table('user_facilities')
    op.drop_table('separators')
    op.drop_table('facilities')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
