"""empty message

Revision ID: e00f2ee1aefb
Revises: f94d1e2a5e76
Create Date: 2021-03-26 17:44:12.354671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00f2ee1aefb'
down_revision = 'f94d1e2a5e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('facilities_company_id_key', 'facilities', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('facilities_company_id_key', 'facilities', ['company_id'])
    # ### end Alembic commands ###
